apiVersion: v2
name: mcp-servers
description: A Helm chart for deploying MCP (Model Context Protocol) servers using the Toolhive operator
type: application
version: 0.5.5
appVersion: "0.5.5"

keywords:
  - mcp
  - toolhive
  - model-context-protocol
