{{- if .Values.oracle.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oracle23ai.serviceAccountName" . }}
  labels:
    {{- include "oracle23ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  {{- with .Values.oracle.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.oracle.serviceAccount.automount }}
{{- end }}