apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle23ai.fullname" . }}
  labels:
    {{- include "oracle23ai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: oracle
      protocol: TCP
      name: oracle
    {{- if .Values.monitoring.enabled }}
    - port: {{ .Values.monitoring.exporterPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "oracle23ai.selectorLabels" . | nindent 4 }}