apiVersion: v2
name: keycloak
description: A Helm chart for deploying Keycloak on OpenShift
type: application
version: 0.1.0
appVersion: "26.0.7"

keywords:
  - keycloak
  - sso
  - identity
  - authentication
  - oauth
