kind: Secret
apiVersion: v1
metadata:
  name: minio
  labels:
    {{- include "minio.labels" . | nindent 4 }}
data:
  user: {{ .Values.secret.user | b64enc | quote }}
  password: {{ .Values.secret.password | b64enc | quote }}
  host: {{ .Values.secret.host | b64enc | quote }}
  port: {{ .Values.secret.port | b64enc | quote }}
type: Opaque
