{{- if and .Values.enabled .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.resourceName" . }}-config
  namespace: {{ include "mysql.namespace" . }}
  labels:
    app: {{ include "mysql.resourceName" . }}
    {{- include "mysql.labels" . | nindent 4 }}
data:
  {{- if .Values.config.mycnf }}
  my.cnf: |
    {{- .Values.config.mycnf | nindent 4 }}
  {{- end }}
  {{- range $key, $value := .Values.config.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

