{{- if .Values.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.resourceName" . }}
  namespace: {{ include "mysql.namespace" . }}
  labels:
    app: {{ include "mysql.resourceName" . }}
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-name: {{ .Values.database | quote }}
  database-user: {{ .Values.user | quote }}
  database-password: {{ .Values.password | quote }}
  database-root-password: {{ .Values.rootPassword | quote }}
{{- end }}

