{{- if .Values.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.resourceName" . }}
  namespace: {{ include "mysql.namespace" . }}
  labels:
    app: {{ include "mysql.resourceName" . }}
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: mysql
      port: {{ .Values.port | default 3306 }}
      targetPort: mysql
      protocol: TCP
  selector:
    app: {{ include "mysql.resourceName" . }}
    deployment: {{ include "mysql.resourceName" . }}
{{- end }}

