{{- if .Values.notebook.create }}
apiVersion: v1
kind: Secret
metadata:
  name: rag-pipeline-secrets
type: Opaque
stringData:
  MINIO_ENDPOINT: "http://{{ .Values.minio.secret.host }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.minio.secret.port }}"
  MINIO_ACCESS_KEY: "{{ .Values.minio.secret.user }}"
  MINIO_SECRET_KEY: "{{ .Values.minio.secret.password }}"
  LLAMASTACK_BASE_URL: "http://llamastack.{{ .Release.Namespace }}.svc.cluster.local:8321"
  DS_PIPELINE_URL: "https://ds-pipeline-dspa.{{ .Release.Namespace }}.svc.cluster.local:8888"
{{- end }}