name: Lint MySQL Helm Chart

on:
  pull_request:
    paths:
      - 'mysql/helm/**'
  push:
    branches: [main]
    paths:
      - 'mysql/helm/**'

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Lint Helm Chart
        run: helm lint mysql/helm
