{{- if .Values.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-registry.resourceName" . }}-db-secret
  namespace: {{ include "model-registry.namespace" . }}
  labels:
    app: {{ include "model-registry.resourceName" . }}
    {{- include "model-registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-host: {{ include "model-registry.mysql.host" . | quote }}
  database-port: {{ .Values.mysql.port | default 3306 | quote }}
  database-name: {{ .Values.mysql.database | quote }}
  database-user: {{ .Values.mysql.user | quote }}
  database-password: {{ .Values.mysql.password | quote }}
  database-connection-string: {{ include "model-registry.mysql.connectionString" . | quote }}
{{- end }}
