{{- if .Values.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-registry.resourceName" . }}-db-secret
  namespace: {{ include "model-registry.namespace" . }}
  labels:
    app: {{ include "model-registry.resourceName" . }}
    {{- include "model-registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-host: {{ include "model-registry.postgres.host" . | quote }}
  database-port: {{ .Values.postgres.port | default 5432 | quote }}
  database-name: {{ .Values.postgres.database | quote }}
  database-user: {{ .Values.postgres.user | quote }}
  database-password: {{ .Values.postgres.password | quote }}
  database-connection-string: {{ include "model-registry.postgres.connectionString" . | quote }}
{{- end }}
